mysite/autoservice/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.info, name='info'),
    path('owner_cars/', views.owner_cars, name='owner_cars'),
    path('owner_car/<int:owner_car_id>', views.owner_car, name='owner_car'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('search/', views.search, name='search'),
    path('orders/<int:pk>', views.OrderDetailView.as_view(), name='order'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('myorders/', views.UserOrderListView.as_view(), name='my_orders'),
    path('myorders/<int:pk>', views.UserOrderDetailView.as_view(), name='my_order'),
    path('myorders/new', views.UserOrderCreateView.as_view(), name='my_order-new'),
    path('myorders/<int:pk>/update', views.UserOrderUpdateView.as_view(), name='my-order-update'),
    path('myorders/<int:pk>/delete', views.UserOrderDeleteView.as_view(), name='my-order-delete'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('autoservice/', include('autoservice.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/autoservice/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

import pytz
utc = pytz.UTC


# Create your models here.

class Service(models.Model):
    name = models.CharField(verbose_name=_('Name'), max_length=200)
    price = models.FloatField(verbose_name=_("Price"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')


class Car(models.Model):
    manufacturer = models.CharField(verbose_name=_('Manufacturer'), max_length=200)
    model = models.CharField(verbose_name=_('Model'), max_length=200)
    engine = models.CharField(verbose_name=_('Engine'), max_length=200)

    def __str__(self):
        return f"{self.manufacturer} {self.model}, {self.engine}"

    class Meta:
        verbose_name = _('Car')
        verbose_name_plural = _('Cars')


class OwnerCar(models.Model):
    year = models.IntegerField(_('Year'), null=True)
    owner = models.ForeignKey(User, verbose_name=_("Owner"), on_delete=models.SET_NULL, null=True, blank=True)
    car = models.ForeignKey('Car', verbose_name=_("Model"), on_delete=models.SET_NULL, null=True)
    licence_plate = models.CharField(verbose_name=_('Licence plate'), max_length=200)
    vin_code = models.CharField(verbose_name=_('VIN code'), max_length=200)
    photo = models.ImageField(verbose_name=_('Photo'), upload_to='cars', null=True)
    description = HTMLField(verbose_name=_("Description"), null=True)

    def __str__(self):
        return f"{self.owner}: {self.car}, {self.licence_plate}, {self.vin_code}"

    class Meta:
        verbose_name = _('Owner Car')
        verbose_name_plural = _('Owners Cars')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        img = Image.open(self.photo.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)


class Order(models.Model):
    owner_car = models.ForeignKey('OwnerCar', verbose_name=_("Model"), on_delete=models.SET_NULL, null=True)
    due_date = models.DateTimeField(verbose_name=_('Due Date'), null=True, blank=True)

    @property
    def final(self):
        total = 0
        lines = OrderLine.objects.filter(order=self.id)
        for line in lines:
            total += line.service.price * line.qty
        return total

    def __str__(self):
        return f"{self.owner_car}: {self.owner_car.owner}, {self.due_date}"

    @property
    def is_overdue(self):
        if self.due_date and datetime.today().replace(tzinfo=utc) > self.due_date.replace(tzinfo=utc):
            return True
        return False

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    STATUS = (
        ('r', _('Draft')),
        ('i', _('In progress')),
        ('d', _('Done')),
        ('c', _('Canceled')),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='r',
        help_text=_('Status'),
    )

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse('my_order', args=[str(self.id)])

class OrderLine(models.Model):
    order = models.ForeignKey('Order', verbose_name=_("Order"), on_delete=models.SET_NULL, null=True, related_name='lines')
    service = models.ForeignKey('Service', verbose_name=_("Service"), on_delete=models.SET_NULL, null=True)
    qty = models.IntegerField(_("Quantity"))

    @property
    def total(self):
        return self.service.price * self.qty

    class Meta:
        verbose_name = _('Order Line')
        verbose_name_plural = _('Order Lines')

    def __str__(self):
        return f"{self.order}: {self.service}, {self.qty}"


class OrderComment(models.Model):
    order = models.ForeignKey('Order', on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(verbose_name=_("Date"), auto_now_add=True)
    content = models.TextField(_('Comment'), max_length=2000)

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(verbose_name=_("Photo"), default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        img = Image.open(self.photo.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

mysite/autoservice/forms.py
from .models import OrderComment, Profile
from django.contrib.auth.models import User
from django import forms


class OrderCommentForm(forms.ModelForm):
    class Meta:
        model = OrderComment
        fields = ('content', 'order', 'user',)
        widgets = {'order': forms.HiddenInput(), 'user': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

mysite/autoservice/views.py
from django.shortcuts import render, get_object_or_404, reverse
from .models import Service, Car, Order, OwnerCar
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import OrderCommentForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)

def info(request):
    num_services = Service.objects.all().count()
    num_cars = OwnerCar.objects.all().count()
    num_orders_done = Order.objects.filter(status__exact='d').count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_services': num_services,
        'num_cars': num_cars,
        'num_orders_done': num_orders_done,
        'num_visits': num_visits,
    }
    return render(request, 'info.html', context=context)


def owner_cars(request):
    paginator = Paginator(OwnerCar.objects.all(), 1)
    page_number = request.GET.get('page')
    paged_cars = paginator.get_page(page_number)
    return render(request, 'owner_cars.html', {'cars': paged_cars})


def owner_car(request, owner_car_id):
    single_owner_car = get_object_or_404(OwnerCar, pk=owner_car_id)
    return render(request, 'owner_car.html', {'owner_car': single_owner_car})


class OrderListView(ListView):
    model = Order
    paginate_by = 6
    template_name = 'orders.html'


class OrderDetailView(FormMixin, DetailView):
    model = Order
    template_name = 'order.html'
    form_class = OrderCommentForm

    # nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse('order', kwargs={'pk': self.object.id})

    # įtraukiame formą į kontekstą, inicijuojame pradinę 'book' reikšmę.
    def get_context_data(self, *args, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['form'] = OrderCommentForm()
        return context

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # štai čia nurodome, kad knyga bus būtent ta, po kuria komentuojame, o vartotojas bus tas, kuris yra prisijungęs.
    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.user = self.request.user
        form.save()
        return super(OrderDetailView, self).form_valid(form)


def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = OwnerCar.objects.filter(
        Q(licence_plate__icontains=query) | Q(vin_code__icontains=query) | Q(car__manufacturer__icontains=query) | Q(
            car__model__icontains=query))
    return render(request, 'search.html', {'cars': search_results, 'query': query})



@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _('Username %(username)s already exists!') % {'username': username})
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _('Email %(email)s already exists!') % {'email': email})
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    return redirect('login')
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'register.html')


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, _('Profile updated'))
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)


class UserOrderListView(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'user_orders.html'

    def get_queryset(self):
        return Order.objects.filter(owner_car__owner=self.request.user)


class UserOrderDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'user_order.html'
    form_class = OrderCommentForm

    # nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse('my_order', kwargs={'pk': self.object.id})

    # įtraukiame formą į kontekstą, inicijuojame pradinę 'book' reikšmę.
    def get_context_data(self, *args, **kwargs):
        context = super(UserOrderDetailView, self).get_context_data(**kwargs)
        context['form'] = OrderCommentForm()
        return context

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # štai čia nurodome, kad knyga bus būtent ta, po kuria komentuojame, o vartotojas bus tas, kuris yra prisijungęs.
    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.user = self.request.user
        form.save()
        return super(UserOrderDetailView, self).form_valid(form)


class UserOrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    fields = ['owner_car', 'due_date']
    template_name = 'user_order_form.html'

    def get_form(self, *args, **kwargs):
        form = super(UserOrderCreateView, self).get_form(*args, **kwargs)
        form.fields['owner_car'].queryset = OwnerCar.objects.filter(owner=self.request.user)
        return form


class UserOrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Order
    fields = ['owner_car', 'due_date']
    template_name = 'user_order_form.html'

    def get_form(self, *args, **kwargs):
        form = super(UserOrderUpdateView, self).get_form(*args, **kwargs)
        form.fields['owner_car'].queryset = OwnerCar.objects.filter(owner=self.request.user)
        return form

    def test_func(self):
        order = self.get_object()
        return self.request.user == order.owner_car.owner


class UserOrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Order
    success_url = "/autoservice/myorders/"
    template_name = 'user_order_delete.html'

    def test_func(self):
        order = self.get_object()
        return self.request.user == order.owner_car.owner

mysite/autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    <title>{% trans "Autoservice" %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
    <div class="container">
        <a class="navbar-brand" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cursor"
                 viewBox="0 0 16 16">
                <path d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103zM2.25 8.184l3.897 1.67a.5.5 0 0 1 .262.263l1.67 3.897L12.743 3.52 2.25 8.184z"/>
            </svg>
            {% trans "Autoservice" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info' %}">{% trans "Home" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'owner_cars' %}">{% trans "Vehicles" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders' %}">{% trans "Orders" %}</a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}"/>
                        <select name="language" onchange="this.form.submit()">
                            {% load static %}
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% for lang in LANGUAGES %}
                            <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
                                {{ lang.0 }}
                            </option>
                            {% endfor %}
                        </select>
                    </form>
                </li>
                <li>
                    <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                        <input name="query" class="form-control" type="text" placeholder="Paieška">
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    {{ user.get_username }}</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_orders' %}">{% trans "My Orders" %}</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">{% trans "Logout" %}</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">{% trans "Login" %}</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">{% trans "Register" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

mysite/autoservice/templates/info.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Autoservice" %}</h1>
  <p>{% trans "Welcome to Autoservice!" %}</p>
  <p>{% trans "Autoservice statistics:" %}</p>
  <ul>
    <li><strong>{% trans "Services:" %}</strong> {{ num_services }}</li>
    <li><strong>{% trans "Vehicles:" %}</strong> {{ num_cars }}</li>
    <li><strong>{% trans "Orders done:" %}</strong> {{ num_orders_done }}</li>
    <p>{% trans "Your visits:" %} {{ num_visits }}</p>
  </ul>
{% endblock %}

mysite/autoservice/templates/order.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container owner_car">
    <h2>{% trans "Vehicle:" %}: {{ order.owner_car }}</h2>
    <hr/>
    <p>{% trans "Deadline:" %} {{ order.due_date }}</p>
    </hr>
    </br>
</div>
<h4>{% trans "Lines:" %}</h4>
{% for line in order.lines.all %}
<hr>
<p>
    {{ line.service }} ({{ line.service.price }}) - {{ line.qty }}: {{ line.total}}
</p>
{% endfor %}
<h2>{% trans "Total:" %} {{ order.final }}</h2>

{% if user.is_authenticated %}
<div class="fieldWrapper">
    <hr>
    <br/>
    <h4>{% trans "Leave a comment:" %}</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.content }}</br>
        <input type="submit" value="{% blocktrans %}Publish{% endblocktrans %}">
    </form>
</div>
{% endif %}
</br>
<h4>{% trans "Comments:" %}</h4>
{% if order.ordercomment_set.all %}
{% for commment in order.ordercomment_set.all %}
<hr>
<strong>{{ commment.user }}</strong>, <em>{{ commment.date_created}}</em>
<p>{{ commment.content }}</p>
{% endfor %}
{% else %}
<p>{% trans "No comments" %}</p>
{% endif %}

{% endblock %}

mysite/autoservice/templates/orders.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "Orders list" %}</h1>
{% if order_list %}
<div class="row">
    {% for order in order_list %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
            <img class="rounded-circle account-img" src="{{ order.owner_car.owner.profile.photo.url }}">
            <div class="card-body">
                <a href="{{ order.id }}">{{ order.owner_car }}</a> ({{order.due_date}})
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>{% trans "No orders" %}</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; {% trans "first" %}</a>
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "back" %}</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{% trans "next" %}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "last" %} &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/autoservice/templates/owner_car.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
    <div class="container owner_car">
      {% if owner_car.photo %}
            <img src="{{ owner_car.photo.url }}" class="card-img-top" alt="...">
      {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top">
      {% endif %}
    <h2>{% trans "Vehicle:" %} {{ owner_car.car }}</h2>
    <hr/>
    <p>{% trans "Owner:" %} {{ owner_car.owner }}</p>
        <hr/>
    <p>{% trans "Year:" %} {{ owner_car.year }}</p>
        <hr/>
    <p>{% trans "Licence Plate:" %} {{ owner_car.licence_plate }}</p>
        <hr/>
    <p>{% trans "VIN code:" %} {{ owner_car.vin_code }}</p>
        <hr/>
    </hr>
    </br>
    <p>{{ owner_car.description | safe }}</p>
    </div>
{% endblock %}

mysite/autoservice/templates/owner_cars.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load static %}
  <h1>{% trans "Vehicles:" %}</h1>

<div class="row">
{% for car in cars %}
<div class="col-md-4 d-flex align-items-stretch">
  <div class="card mb-4 shadow-sm">
      {% if car.photo %}
            <img src="{{ car.photo.url }}" class="card-img-top" alt="...">
      {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top">
      {% endif %}
      <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">{{ car.owner }}</h6>
          <p class="card-text"><a href="{% url 'owner_car' car.id %}">{{ car.car }}</a></p>
      </div>
  </div>
</div>
{% endfor %}
<div class="container puslapiai">
    <nav aria-label="...">
        {% if cars.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in cars.paginator.page_range %}
                    {% if cars.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

mysite/autoservice/templates/search.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Search" %} "{{query}}" {% trans "results:" %}</h1>
  </br>
  {% if cars %}
  <ul>
    {% for car in cars %}
      <li>
        <a href="{% url 'owner_car' car.id %}">{{ car }}</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>{% trans "Oops. Nothing found :(" %}</p>
  {% endif %}

  {% endblock %}

mysite/autoservice/templates/user_order.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container owner_car">
    {% if order.owner_car.photo %}
    <div><img class="" src="{{order.owner_car.photo.url}}"></div>
    {% endif %}
    <h2>{% trans "Vehicle:" %} {{ order.owner_car }}</h2>
    <hr/>
    <p>{% trans "Deadline:" %} {{ order.due_date }}</p>
    </hr>
    </br>
</div>
{% if order.owner_car.owner == user %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-order-update' order.id %}">{% trans "Edit" %}</a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'my-order-delete' order.id %}">{% trans "Delete" %}</a>
</div>
{% endif %}

<h4>{% trans "Lines:" %}</h4>
{% for line in order.lines.all %}
<hr>
<p>
    {{ line.service }} ({{ line.service.price }}) - {{ line.qty }}: {{ line.total}}
</p>
{% endfor %}
<h2>{% trans "Total:" %} {{ order.final }}</h2>

{% if user.is_authenticated %}
<div class="fieldWrapper">
    <hr>
    <br/>
    <h4>{% trans "Leave a comment:" %}</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.content }}</br>
        <input type="submit" value="{% blocktrans %}Publish{% endblocktrans %}">
    </form>
</div>
{% endif %}
</br>
<h4>{% trans "Comments:" %}</h4>
{% if order.ordercomment_set.all %}
{% for commment in order.ordercomment_set.all %}
<hr>
<strong>{{ commment.user }}</strong>, <em>{{ commment.date_created}}</em>
<p>{{ commment.content }}</p>
{% endfor %}
{% else %}
<p>{% trans "No comments" %}</p>
{% endif %}

{% endblock %}